image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Sync Bitbucket to GitHub
        script:
          - apt-get update
          - apt-get install -y git
          - git clone https://$BITBUCKET_USERNAME:$BITBUCKET_APP_PASSWORD@bitbucket.org/ag-sound/case-chronicle.git
          - cd cases
          - git remote add github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/AlejandroGispert/case-chronicle-webapp.git
          - git config user.email "alejandrobusiness2022@gmail.com"
          - git config user.name "AlejandroGispert"
          - git push github main --force
